import { SettingBlock } from "./blocks/SettingBlock";

export type VueComponent = {
    new(): import("vue").Component;
}

export interface Block {
    /**
     *  ID is not required for creating a draggable block,
     *  it will be generated by system on drop, and it's need to be tracked and remove
     *  If you are creating a droppablele component in that case you will need to add uuid on drop.
     */
    id?: string;

    /**
     * Name needs to be unique, it's a key identifier for draggable block.
     * Name must be alphanumeric and unique
     */
    name: string;

    /**
     * Just a basic vue component and the component accept blockInfo as props
     */
    component: VueComponent | undefined;

    /**
     * Just a basic vue component adn the component accept blockInfo as props
     */
    optionComponent: VueComponent;

    /**
     * Options accept Record<string, any> use to modify design, text and other ui staff from options to preview
     */
    options: Record<string, any>;

    children?: Block[] | { [key: string | number]: Block[] };

    /**
     * Title will appear in the block section
     */
    title: string;

    /**
     * Icon will appear in the block section
     */
    icon: string;

    /**
     * Preview will appear on hover on block
     */
    previewImg?: string;

    type: BlockType
}

export type BlockType = 'element' | 'ui-component' | 'layout' | 'setting';

export type Language = 'sk' | 'en'

export type Mode = 'editor' | 'editor_preview' | 'preview'

export type Device = 'desktop' | 'tab' | 'mobile' | 'custom'

export interface UploaderConfig {
    url: string;
    headers?: Record<string, string>;
}

export interface Resolution {
    width: String | number | number
    height: String | number | number
}
export interface Config {
    language: Language;
    uploader?: UploaderConfig;
    resolution?: Resolution
    device: Device
    showDeviceBar?: boolean
}

export interface SavePayload {
    renderList: Block[]
    settings: SettingBlock
}

export interface MarginOptions {
    marginLeft?: string | number | undefined
    marginRight?: string | number | undefined
    marginTop?: string | number | undefined
    marginBottom?: string | number | undefined
}

export interface BorderRadiusOptions {
    borderBottomLeftRadius?: string | number | undefined
    borderBottomRightRadius?: string | number | undefined
    borderTopRightRadius?: string | number | undefined
    borderTopLeftRadius?: string | number | undefined
}